name: samples

on:
  pull_request:
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  swift-build-run:
    strategy:
      matrix:
        # Test build with debug and release configs (whether or not DEBUG is set and optimization level)
        build: [build, archive]
        os: [macos-13]
        include:
          - os: macos-13
            xcode: Xcode_15.0.1
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Xcode
      run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app/Contents/Developer
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: Build the sample
      run: scripts/third_party/travis/retry.sh scripts/build.sh GenerativeAISample iOS ${{ matrix.build }} Examples/GenerativeAISample/GenerativeAISample.xcodeproj
